server.port=8098

spring.application.name= fortune-service

# ===============================
# MySQL Datasource
# ===============================
spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver
spring.datasource.url= jdbc:mysql://8.135.35.245:3306/sys?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=true&tinyInt1isBit=false
spring.datasource.username= hidden
spring.datasource.password= Hidden1009..

logging.level.com.zaxxer.hikari=INFO
logging.level.org.mybatis=DEBUG
logging.level.org.springframework.jdbc=DEBUG
